name: VentureLite
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/6e1f648d-11d5-4759-8500-cbb5e331dacd.png'
layout_spectrum: 0.34024
typography_spectrum: 0.47553
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/a01ecdea-bcdb-40c6-b541-181e9ac8fc7e.svg'
title: Intelligente lamper til lysbranchen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
  brandStrength: 0.46703077433630824
  lightness: 0.5771294175647199
  saturation: 0.5645855558104813
  rhythmicContrast: 0.449552055913955
purpose: []
